### ISSUE TITLE
Error sorting Plugins (SkyrimSE)

### ISSUE THREAD

**Issue by Wawwior** [limo-app/limo#121]
Sorting plugins gives me this error: `yaml-cpp: error at line 3276, column 9: bad conversion: 'content' key missing from 'message' object`
I am using the v0.21 masterlist for skyrimse, which is being downloaded correctly.

From Arch/AUR:
limo-git: r138.662e695-1
libloot: 0.24.5-1
yaml-cpp: 0.8.0-2

masterlist.yaml 3276:9

```yaml
  - name: 'DeadlySpellImpacts( - Two Fire)?\.esp'
    url:
      - link: 'https://www.nexusmods.com/skyrimspecialedition/mods/12939/' < line 3276
        name: 'Deadly Spell Impacts'
```
